import os

def generate_svg(quote_text, output_path="quote.svg", theme="General"):
    # Manual text wrapping (simple version)
    words = quote_text.split()
    lines = []
    current_line = []
    for word in words:
        if len(" ".join(current_line + [word])) > 40:
            lines.append(" ".join(current_line))
            current_line = [word]
        else:
            current_line.append(word)
    lines.append(" ".join(current_line))

    # SVG Template with a nice gradient background
    line_height = 40
    start_y = 250 - (len(lines) * line_height / 2)
    
    tspans = ""
    for i, line in enumerate(lines):
        y_pos = start_y + (i * line_height)
        tspans += f'<tspan x="400" y="{y_pos}" dy="1.2em">{line}</tspan>\n'

    svg_content = f"""<svg width="800" height="500" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#1e3c72;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#2a5298;stop-opacity:1" />
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="3" />
      <feOffset dx="2" dy="2" result="offsetblur" />
      <feComponentTransfer>
        <feFuncA type="linear" slope="0.5" />
      </feComponentTransfer>
      <feMerge>
        <feMergeNode />
        <feMergeNode in="SourceGraphic" />
      </feMerge>
    </filter>
  </defs>
  <rect width="100%" height="100%" fill="url(#grad1)" />
  <rect x="50" y="50" width="700" height="400" fill="none" stroke="white" stroke-width="2" stroke-opacity="0.3" rx="15" />
  
  <text x="400" y="100" font-family="Arial, sans-serif" font-size="24" fill="white" fill-opacity="0.6" text-anchor="middle" font-style="italic">
    Perspective: {theme}
  </text>
  
  <text x="400" y="250" font-family="Georgia, serif" font-size="32" fill="white" text-anchor="middle" filter="url(#shadow)">
    {tspans}
  </text>
  
  <text x="400" y="440" font-family="Arial, sans-serif" font-size="16" fill="white" fill-opacity="0.4" text-anchor="middle">
    Generated by Shitty Quote Engine v2.0
  </text>
</svg>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(svg_content)
    print(f"SVG image saved to: {output_path}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        text = sys.argv[1]
        generate_svg(text)
